# fly.toml app configuration file generated for ngv17 on 2023-11-09T18:21:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ngv17"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  port = 8080
